version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "6000:6000"
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production


