version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - "6000:6000"
    volumes:
      - ./db:/app/db
    environment:
      - NODE_ENV=production
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otelcol:4318/v1/traces
      - OTEL_SERVICE_NAME=mezmo-demo-backend
      - OTEL_TRACES_EXPORTER=otlp
  otelcol:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otelcol-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP

